/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef graphps_TYPES_H
#define graphps_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace graphps {

typedef int32_t VidDtype;

typedef int32_t VdegDtype;

typedef double VvalueDtype;

typedef double VmsgDtype;

class ComponentID;

class VertexData;

typedef struct _ComponentID__isset {
  _ComponentID__isset() : minID(false), maxID(false) {}
  bool minID :1;
  bool maxID :1;
} _ComponentID__isset;

class ComponentID : public virtual ::apache::thrift::TBase {
 public:

  ComponentID(const ComponentID&);
  ComponentID& operator=(const ComponentID&);
  ComponentID() : minID(0), maxID(0) {
  }

  virtual ~ComponentID() throw();
  VidDtype minID;
  VidDtype maxID;

  _ComponentID__isset __isset;

  void __set_minID(const VidDtype val);

  void __set_maxID(const VidDtype val);

  bool operator == (const ComponentID & rhs) const
  {
    if (!(minID == rhs.minID))
      return false;
    if (!(maxID == rhs.maxID))
      return false;
    return true;
  }
  bool operator != (const ComponentID &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ComponentID & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ComponentID &a, ComponentID &b);

inline std::ostream& operator<<(std::ostream& out, const ComponentID& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _VertexData__isset {
  _VertexData__isset() : value(false), msg(false), state(false), outdegree(false) {}
  bool value :1;
  bool msg :1;
  bool state :1;
  bool outdegree :1;
} _VertexData__isset;

class VertexData : public virtual ::apache::thrift::TBase {
 public:

  VertexData(const VertexData&);
  VertexData& operator=(const VertexData&);
  VertexData() : value(0), msg(0), state(0), outdegree(0) {
  }

  virtual ~VertexData() throw();
  VvalueDtype value;
  VmsgDtype msg;
  bool state;
  VdegDtype outdegree;

  _VertexData__isset __isset;

  void __set_value(const VvalueDtype val);

  void __set_msg(const VmsgDtype val);

  void __set_state(const bool val);

  void __set_outdegree(const VdegDtype val);

  bool operator == (const VertexData & rhs) const
  {
    if (!(value == rhs.value))
      return false;
    if (!(msg == rhs.msg))
      return false;
    if (!(state == rhs.state))
      return false;
    if (__isset.outdegree != rhs.__isset.outdegree)
      return false;
    else if (__isset.outdegree && !(outdegree == rhs.outdegree))
      return false;
    return true;
  }
  bool operator != (const VertexData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VertexData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(VertexData &a, VertexData &b);

inline std::ostream& operator<<(std::ostream& out, const VertexData& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
