/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "graphps_constants.h"

namespace graphps {

const graphpsConstants g_graphps_constants;

graphpsConstants::graphpsConstants() {
}

} // namespace

