/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef graphps_CONSTANTS_H
#define graphps_CONSTANTS_H

#include "graphps_types.h"

namespace graphps {

class graphpsConstants {
 public:
  graphpsConstants();

};

extern const graphpsConstants g_graphps_constants;

} // namespace

#endif
